name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp.cluster029.hosting.ovh.net
          user: fqpudvo
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: "/www"
          options: "--delete --ascii"
